CREATE IF NOT EXISTS SCHEMA ${schema2};
USE SCHEMA ${schema2};

CREATE TABLE IF NOT EXISTS ${schema2}.table3 (
    ID INT AUTOINCREMENT PRIMARY KEY,
    ADDRESS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ${schema2}.table4 (
    ID INT AUTOINCREMENT PRIMARY KEY,
    PHONE_NUMBER STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);