flyway.url=jdbc:snowflake://UJFTMOX-GMB66286.snowflakecomputing.com/?db=MYDB_TEST&warehouse=compute_wh&role=sysadmin
flyway.placeholders.schema1=SCHEMA1
flyway.placeholders.schema2=SCHEMA2
flyway.locations=filesystem:scripts
